### ISSUE TITLE
What is the state of koa-webpack-dev?

### ISSUE THREAD

**Issue by ElegantScripting** [kitmi/koa-webpack-dev#2]
The question is in the title.

I'm wondering:
1. **What is the state of koa-webpack-dev?**
2. **Why should I use it?**
3. **How does koa-webpack-dev differ from the traditional webpack-dev-server?**

**Comment by rockie** [comment]
1. not much feature, but ready to use
2. if you are working on a project using koa, you may find it useful, just put it as a middleware
3. koa-webpack-dev is a middleware, the traditional webpack-dev-server is a stand-alone service

**Comment by ElegantScripting** [comment]
Good answers, thanks.
