### ISSUE TITLE
koa v2 support

### ISSUE THREAD

**Issue by chompomonim** [kitmi/koa-webpack-dev#3]
Is this middleware Koa2 ready? Is so, how I can use it?

**Comment by xiaoweb** [comment]
koa-webpack-dev how to support https？

**Comment by rockie** [comment]
@chompomonim not koa2 ready. 

@xiaoweb A common practice is to use a front-end proxy like nginx as the SSL server and forward the https requests to upstream node process. However, just remember this simple koa-webpack-dev is not for production use. It compiles all source code into memory and without fault tolerance.
